name = "tbc-members-core-ui"
type = "javascript"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true
compatibility_date = "2023-06-13"

[site]
bucket = "./build"
entry-point = "workers-site"

[env.production]
zone_id = "${CF_ZONE_ID}"
route = "https://www.dev.techbychoice.org/*"
