# Generated by Django 4.2.13 on 2024-06-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_extended_max_char_length_mutiple_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='company_job_status_4f29ad_idx'),
        ),
    ]
